FROM node:lts
# Declaring env
#ENV NODE_ENV development

# Setting up the work directory
WORKDIR /app

# Copying all the files in our project
COPY . .

RUN npm install

# Starting our application
CMD ["npm", "run","dev"]