version: "3.8"
services:
    db:
        image: "mysql:latest"
        volumes:
            - data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        networks:
            - backend
    server:
        build: ./server
        ports:
            - "8000:8000"
        networks:
            - frontend
            - backend

    client:
        build: ./client
        ports:
            - "5173:5173"
        networks:
            - frontend

networks:
    backend:
    frontend:
volumes:
    data:
