version: "3.8"
services:
    db:
        image: "mysql:latest"
        volumes:
            - data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        networks:
            - backend
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10
    server:
        build: ./server
        volumes: # volumes used during development
            - ./server/app:/var/www/html/app
            - ./server/routes:/var/www/html/routes
        ports:
            - "80:80"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        networks:
            - backend
        command: sh -c "php artisan migrate --force && apache2-foreground"
        depends_on:
            db:
                condition: service_healthy
    client:
        build: ./client
        volumes: # volumes used during development
            - ./client/src:/app/src
        ports:
            - "8080:8080"
networks:
    backend:
volumes:
    data:
