spring:
    datasource:
        url: jdbc:mysql://db:3306/advJava?connectTimeout=3000&socketTimeout=3000
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
            # format_sql: true
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
            - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
management:
    health:
        mongo:
            enabled: false
#logging:
#    level:
#        org.zalando.logbook: TRACE
#        com.pseudoorganization.pseudosystemsintegration: TRACE
