spring:
  datasource:
    url: jdbc:mysql://localhost:3306/advJava?useSSL=false
    username: root
    password: radio
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 1000
        order_inserts: true
      # format_sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
management:
  health:
    mongo:
      enabled: false
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: DEBUG
    org.zalando.logbook: TRACE
    com.pseudoorganization.pseudosystemsintegration: TRACE
jwt:
  secretKey: "sN9M/k8wu4t/Eahhy1kNy7InYn1WuCKMULusWiT3NQU="
server:
  port: 8081
