spring:
  datasource:
    url: jdbc:mysql://localhost:3306/advJava?useSSL=false
    username: root
    password: radio
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      # format_sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
management:
  health:
    mongo:
      enabled: false
logging:
  level:
    org.zalando.logbook: TRACE
    com.pseudoorganization.pseudosystemsintegration: TRACE