FROM composer:lts as build
COPY . /app/
#PRODUCTION: --prefer-dist --no-dev --optimize-autoloader
RUN composer install --no-interaction

FROM php:8.1-apache-buster as production

#ENV APP_ENV=production
#ENV APP_DEBUG=false

#PRODUCTION: docker-php-ext-configure opcache --enable-opcache
RUN docker-php-ext-install pdo pdo_mysql

#PRODUCTION: COPY docker/php/conf.d/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
COPY --from=build /app /var/www/html
COPY docker/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY docker/php.ini $PHP_INI_DIR/php.ini

RUN php artisan key:generate && \
    php artisan jwt:secret && \
    chmod 777 -R /var/www/html/storage/ && \
    a2enmod rewrite