# Use the official OpenJDK image as the base image
FROM openjdk:17-jdk-slim AS build
WORKDIR /app

# Copy Maven Wrapper and source code into the container
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src/

# Make mvnw executable and ensure line endings are correct
RUN chmod +x mvnw && \
    sed -i 's/\r$//' mvnw && \
    ./mvnw -B clean install -DskipTests

# Create the final image
FROM openjdk:17-jdk-slim AS final
WORKDIR /app
COPY --from=build /app/target/adv-java-0.0.1-SNAPSHOT.jar .
CMD ["java", "-jar", "adv-java-0.0.1-SNAPSHOT.jar"]

